name: Run Marketing Forecast

on:
  schedule:
    - cron: '0 3 * * *'   # runs daily
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install prophet psycopg2-binary gspread oauth2client pandas numpy nbconvert ipykernel
          python -m ipykernel install --user

      - name: Run notebook
        env:
          REDSHIFT_HOST: ${{ secrets.REDSHIFT_HOST }}
          REDSHIFT_USER: ${{ secrets.REDSHIFT_USER }}
          REDSHIFT_PASSWORD: ${{ secrets.REDSHIFT_PASSWORD }}
          REDSHIFT_DB: ${{ secrets.REDSHIFT_DB }}
        run: |
          jupyter nbconvert --execute Python_Forecast_Gsheet_Google_Ads.ipynb --to notebook
